MODE : "DEFAULT"
MAIL_USERNAME : ""
MAIL_PASSWORD : ""
MAIL_FROM : ""
MAIL_PORT : 465
MAIL_SERVER : "smtp.gmail.com"
MAIL_STARTTLS : False
MAIL_SSL_TLS : True
USE_CREDENTIALS : True
VALIDATE_CERTS : True